name: show_toast
description: "A minimal and customizable implementation for showing toast messages."
version: 0.3.0
homepage: https://github.com/Yoeri-z/toast_messages
repository: https://github.com/Yoeri-z/toast_messages
issue_tracker: https://github.com/Yoeri-z/toast_messages/issues

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
